export const REDUCER_CONSTANT = {
  LOADER_START: "LOADER_START",
  LOADER_OFF: "LOADER_OFF",
  FETCH_LIST: "FETCH_LIST",
  DELETE_POST: "DELETE_POST",
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
};
